function setGlobalConstants() {
	GC = {
		//bag
		EQUIP_X: 305,
		EQUIP_Y: 400,
		EQUIP_W: 60,
		EQUIP_H: 25,

		DROP_X: 305,
		DROP_Y: 440,
		DROP_W: 60,
		DROP_H: 25,

		USE_X: 305,
		USE_Y: 480,
		USE_W: 60,
		USE_H: 25,

		GEM_BUTTON_X: 400,
		GEM_BUTTON_Y: 330,
		GEM_BUTTON_W: 100,
		GEM_BUTTON_H: 25,

		//inventory screen
		INV_LINE_HEIGHT: 25,
		INV_INDENT: 20,

		INV_BOX_X: 600,
		INV_BOX_Y: 100,
		INV_BOX_W: 240,
		INV_BOX_H: 240,
		INV_CANVAS_HELMET_X: 720,
		INV_CANVAS_HELMET_Y: 140, 
		INV_CANVAS_ARMOR_X: 720,
		INV_CANVAS_ARMOR_Y: 215,
		INV_CANVAS_SHIELD_X: 645,
		INV_CANVAS_SHIELD_Y: 225,
		INV_CANVAS_WEAPON_X: 795,
		INV_CANVAS_WEAPON_Y: 225,
		INV_CANVAS_BOOTS_X: 720,
		INV_CANVAS_BOOTS_Y: 290,

		INV_SWAP_X: 610,
		INV_SWAP_Y: 290,
		INV_SWAP_W: 70,
		INV_SWAP_H: 25, 

		UNEQUIP_X: 760,
		UNEQUIP_Y: 290,
		UNEQUIP_W: 73,
		UNEQUIP_H: 25,

		ITEM_SELECT_BOX_X: 350,
		ITEM_SELECT_BOX_Y: 120,
		ITEM_SELECT_BOX_W: 200,
		ITEM_SELECT_BOX_H: 200,

		GEM_BOX_X: 275,
		GEM_BOX_W: 50,
		GEM_BOX_H: 50,
		GEM_BOX_SPACING: 75,
		GEM_BOX_BORDER: 5,

		BAG_SLOTS_X: 60,
		BAG_SLOTS_Y: 60,
		BAG_ROW_SLOTS: 10,
		BAG_SLOTS: 20,

		//HUD (was canvas2)
		EXP_X: 530,
		EXP_Y: canvas.height - 89,
		EXP_W: 400,
		EXP_H: 15,

		SPELL_OPTIONS_FIRST_X: 450,
		SPELL_OPTIONS_Y: canvas.height-55,
		SPELL_OPTIONS_W: 50,
		SPELL_OPTIONS_H: 50,
		NUM_SPELLS_SHOWN: 10,

		AURA_OPTIONS_FIRST_X: 332,
		AURA_OPTIONS_SPACING: 50,
		AURA_OPTIONS_Y: canvas.height - 82,
		AURA_OPTIONS_BOX_W: 40,
		AURA_OPTIONS_BOX_H: 30,

		POWERUP_Y: canvas.height-75,

		APPLE_X: canvas.width/2 + 273,
		GRAPES_X: canvas.width/2 + 353,

		COINS_X: 355,
		COINS_Y: canvas.height - 20,

		//stats screen 
		BUTTON_GAP: 60,
		HEALTH_BUTTON_Y: 140,
		STAT_BUTTONS_X: canvas.width/2-410,
		STAT_BUTTONS_W: 50,
		STAT_BUTTONS_H: 50,

		SPELLS_AREA_X: canvas.width/2-130,
		SPELLS_AREA_Y: 100,
		SPELLS_AREA_W: 550,
		SPELLS_AREA_H: 400, 

		SPELLS_ROW_GAP: 30,
		SPELLS_BOX_DIMS: 50,

		//questClass
		QUEST_BUTTONS_W: 200,
		QUEST_BUTTONS_H: 40,
		GAP_Y: 10,

		QUEST_BOX_W: 500,
		QUEST_BOX_H: 375,

		LINE_SPACE: 25,

		DISPLAY_BOX_H: 245,
		QUEST_OPTIONS_BUTTONS_W: 100,
		QUEST_OPTIONS_BUTTONS_H: 20,


		//levelClass (map visual)
		MAP_X: 150 * 1.5,
		MAP_Y: 50 * 1.5,

		//these are overrideen in levelClass.js, check it out later
		MAP_LEVEL_W: 150,
		MAP_LEVEL_H: 96,
		MAP_LEVEL_GAP: 30,
		MAP_CONNECT_W: 15,

		MAP_CHAR_BUTTON_W: 100,
		MAP_CHAR_BUTTON_H: 30,

		//shopScreen
		SHOP_BAG_X: 290,
		SHOP_BAG_Y: 390,
		SHOP_ITEM_SELECT_BOX_X: 930,
		SHOP_ITEM_SELECT_BOX_Y: 87,

		SHOP_X: 295,
		SHOP_Y: 120,
		SHOP_W: 590,
		SHOP_H: 250,

		SHOP_SELECTION_AREA_X: 800,
		SHOP_SELECTION_AREA_Y: 130,
		SHOP_SELECTION_AREA_W: 75,
		SHOP_SELECTION_AREA_H: 230,

		SHOP_SLOTS_X: 60,
		SHOP_SLOTS_Y: 60,
		SHOP_ROW_SLOTS: 8,
		SHOP_COL_SLOTS: 4,

		//notifications
		NOTIFICATIONS_X: canvas.width/2 - 100,
		NOTIFICATIONS_START_Y: canvas.height - 102,
		NOTIFICATIONS_Y: canvas.height - 102 - 40,
		NOTIFICATIONS_W: 200,
		NOTIFICATIONS_H: 30,

		//boss
		BOSS_HEALTH_Y: 40,
		BOSS_HEALTH_W: 600,
		BOSS_HEALTH_H: 25,

		//settings
		APPLES_AUTOMATIC_X: canvas.width/2 + 160,
		APPLES_AUTOMATIC_Y: canvas.height/2 - 47,
		GRAPES_AUTOMATIC_X: canvas.width/2 + 160,
		GRAPES_AUTOMATIC_Y: canvas.height/2 - 17,
		MINIMAP_TOGGLE_X: canvas.width/2 + 160,
		MINIMAP_TOGGLE_Y: canvas.height/2 + 120,
		SETTINGS_BUTTONS_W: 20,
		SETTINGS_BUTTONS_H: 20,
		DIFF_SLIDER_Y: canvas.height/2 + 50,

		//audioAdv (settings)
		SLIDER_X: 3*canvas.width/8,
		SLIDER_LENGTH: canvas.width/4,
		SLIDER_HEIGHT: 10,
		TOP_SLIDER_Y: canvas.height/4,
		BOTTOM_SLIDER_Y: canvas.height/4+70,
		SLIDER_RADIUS: 12,

		//dialogue
		DIALOGUE_BOX_X: canvas.width/4,
		DIALOGUE_BOX_Y: 20,
		DIALOGUE_BOX_W: canvas.width/2,
		DIALOGUE_BOX_H: 150,

		//minimap
		MINIMAP_X: 20,
		MINIMAP_Y: 20,
		MINIMAP_W: 250,
		MINIMAP_H: 160,
		MINIMAP_CONNECT_W: 20,
	};
	//minimap

	GC.MINIMAP_MAIN_W = 3*GC.MINIMAP_W/4;
	GC.MINIMAP_MAIN_H = 3*GC.MINIMAP_H/4;
	GC.MINIMAP_MAIN_X = GC.MINIMAP_X + (GC.MINIMAP_W-GC.MINIMAP_MAIN_W)/2;
	GC.MINIMAP_MAIN_Y = GC.MINIMAP_Y + (GC.MINIMAP_H-GC.MINIMAP_MAIN_H)/2;
	GC.MINIMAP_WALL_DIM = GC.MINIMAP_MAIN_W/TRACK_COLS;

	//inventory screen
	GC.BAG_Y = 380;
	GC.BAG_COL_SLOTS = GC.BAG_SLOTS/GC.BAG_ROW_SLOTS;
	GC.BAG_LENGTH = GC.BAG_SLOTS_X*GC.BAG_ROW_SLOTS;
	GC.BAG_HEIGHT = GC.BAG_SLOTS_Y*GC.BAG_COL_SLOTS;
	GC.BAG_X = (canvas.width-GC.BAG_LENGTH)/2;
	GC.EFFECT_WINDOW_X = GC.INV_BOX_X+GC.INV_BOX_W+60;
	GC.EFFECT_WINDOW_Y = 130;
	GC.EFFECT_WINDOW_W = 165;
	GC.EFFECT_WINDOW_H = 180;

	//stats screen
	GC.MANA_BUTTON_Y = GC.HEALTH_BUTTON_Y+GC.BUTTON_GAP
	GC.DAMAGE_BUTTON_Y = GC.MANA_BUTTON_Y+GC.BUTTON_GAP;
	GC.DEFENSE_BUTTON_Y = GC.DAMAGE_BUTTON_Y+GC.BUTTON_GAP;
	GC.ATTACK_RATE_BUTTON_Y = GC.DEFENSE_BUTTON_Y+GC.BUTTON_GAP;
	GC.SPEED_BUTTON_Y = GC.ATTACK_RATE_BUTTON_Y+GC.BUTTON_GAP;
	GC.STAT_TEXT_OFFSET_X = GC.STAT_BUTTONS_W+15;
	GC.STAT_TEXT_OFFSET_Y = GC.STAT_BUTTONS_H/2;
	GC.STAT_CHANGE_X = GC.STAT_BUTTONS_X+220;

	GC.FIRE_SPELL_1X = GC.SPELLS_AREA_X+GC.SPELLS_AREA_W/6;
	GC.LIGHTNING_SPELL_1X = GC.SPELLS_AREA_X+3*GC.SPELLS_AREA_W/6;
	GC.SNOWFLAKE_SPELL_1X = GC.SPELLS_AREA_X+5*GC.SPELLS_AREA_W/6;
	GC.SPELLS_FIRST_ROW_Y = GC.SPELLS_AREA_Y+30;
	GC.SPELLS_SECOND_ROW_Y = GC.SPELLS_FIRST_ROW_Y+GC.SPELLS_BOX_DIMS+GC.SPELLS_ROW_GAP;
	GC.SPELLS_THIRD_ROW_Y = GC.SPELLS_FIRST_ROW_Y+(GC.SPELLS_BOX_DIMS+GC.SPELLS_ROW_GAP)*2;
	GC.SPELLS_FOURTH_ROW_Y = GC.SPELLS_FIRST_ROW_Y+(GC.SPELLS_BOX_DIMS+GC.SPELLS_ROW_GAP)*3;

	GC.SPELLS_EDIT_W = 45;
	GC.SPELLS_EDIT_X = GC.SPELLS_AREA_X+GC.SPELLS_AREA_W-GC.SPELLS_EDIT_W-10;
	GC.SPELLS_EDIT_Y = GC.SPELLS_AREA_Y + 10;
	GC.SPELLS_EDIT_H = 30;

	GC.SKILLS_LAST_BUTTON_X = GC.SPELLS_AREA_X + 30;
	GC.SKILLS_NEXT_BUTTON_X = GC.SPELLS_AREA_X + GC.SPELLS_AREA_W - 30;
	GC.SKILLS_PAGE_BUTTONS_Y = GC.SPELLS_AREA_Y + GC.SPELLS_AREA_H - 40;
	GC.SKILLS_PAGE_BUTTONS_W = 40
	GC.SKILLS_PAGE_BUTTONS_H = 40

	//questClass
	GC.QUEST_BUTTONS_X = GC.MAP_X+50;

	GC.QUEST_BOX_X = GC.QUEST_BUTTONS_X+GC.QUEST_BUTTONS_W+50;
	GC.QUEST_BOX_Y = GC.MAP_Y+50;

	GC.DISPLAY_BOX_X = GC.QUEST_BOX_X+GC.LINE_SPACE;
	GC.DISPLAY_BOX_Y = GC.QUEST_BOX_Y+GC.LINE_SPACE*3.5;
	GC.DISPLAY_BOX_W = GC.QUEST_BOX_W-2*GC.LINE_SPACE;
	GC.QUEST_OPTIONS_BUTTONS_Y = GC.QUEST_BOX_Y+GC.LINE_SPACE*2.5;
	GC.DIALOGUE_BUTTON_X = GC.QUEST_BOX_X+GC.LINE_SPACE;
	GC.REQS_BUTTON_X = GC.DIALOGUE_BUTTON_X+GC.QUEST_OPTIONS_BUTTONS_W+20;
	GC.REWARDS_BUTTON_X = GC.REQS_BUTTON_X+GC.QUEST_OPTIONS_BUTTONS_W+20;

	GC.QUEST_MAP_OPTION_W = 20;
	GC.QUEST_MAP_OPTION_H = 20;
	GC.QUEST_MAP_OPTION_X = GC.DISPLAY_BOX_X + GC.DISPLAY_BOX_W - GC.QUEST_MAP_OPTION_W;
	GC.QUEST_MAP_OPTION_Y = GC.DISPLAY_BOX_Y + GC.DISPLAY_BOX_H + 10;


	//levelClass (map visual)
	GC.MAP_W = canvas.width - 2*GC.MAP_X;
	GC.MAP_H = canvas.height - 4*GC.MAP_Y;
	GC.MAP_WALL_DIM = GC.MAP_LEVEL_W/TRACK_COLS;

	GC.MAP_AREA_X = 300;
	GC.MAP_AREA_Y = 125;
	GC.MAP_AREA_W = GC.MAP_W - 2*(GC.MAP_AREA_X - GC.MAP_X);
	GC.MAP_AREA_H = GC.MAP_H - 2*(GC.MAP_AREA_Y - GC.MAP_Y);

	GC.MAP_CHAR_BUTTON_X = GC.MAP_X + GC.MAP_W - 110;
	GC.MAP_CHAR_BUTTON_Y = GC.MAP_Y + GC.MAP_H - 40;

	GC.TELEPORT_X = GC.MAP_CHAR_BUTTON_X;
	GC.TELEPORT_Y = GC.MAP_CHAR_BUTTON_Y - 40;
	GC.TELEPORT_W = GC.MAP_CHAR_BUTTON_W;
	GC.TELEPORT_H = GC.MAP_CHAR_BUTTON_H;

	//shopScreen
	GC.SHOP_INV_OFFSET_X = 310;
	GC.SHOP_INV_OFFSET_Y = 190;

	GC.SHOP_INV_BOX_X = GC.INV_BOX_X + GC.SHOP_INV_OFFSET_X;
	GC.SHOP_INV_BOX_Y = GC.INV_BOX_Y + GC.SHOP_INV_OFFSET_Y;
	GC.SHOP_INV_BOX_W = GC.INV_BOX_W;
	GC.SHOP_INV_BOX_H = GC.INV_BOX_H;

	GC.SHOP_INV_HELMET_X = GC.INV_CANVAS_HELMET_X + GC.SHOP_INV_OFFSET_X;
	GC.SHOP_INV_HELMET_Y = GC.INV_CANVAS_HELMET_Y + GC.SHOP_INV_OFFSET_Y;
	GC.SHOP_INV_ARMOR_X = GC.INV_CANVAS_ARMOR_X + GC.SHOP_INV_OFFSET_X;
	GC.SHOP_INV_ARMOR_Y = GC.INV_CANVAS_ARMOR_Y + GC.SHOP_INV_OFFSET_Y;
	GC.SHOP_INV_SHIELD_X = GC.INV_CANVAS_SHIELD_X + GC.SHOP_INV_OFFSET_X;
	GC.SHOP_INV_SHIELD_Y = GC.INV_CANVAS_SHIELD_Y + GC.SHOP_INV_OFFSET_Y;
	GC.SHOP_INV_WEAPON_X = GC.INV_CANVAS_WEAPON_X + GC.SHOP_INV_OFFSET_X;
	GC.SHOP_INV_WEAPON_Y = GC.INV_CANVAS_WEAPON_Y + GC.SHOP_INV_OFFSET_Y;
	GC.SHOP_INV_BOOTS_X = GC.INV_CANVAS_BOOTS_X + GC.SHOP_INV_OFFSET_X;
	GC.SHOP_INV_BOOTS_Y = GC.INV_CANVAS_BOOTS_Y + GC.SHOP_INV_OFFSET_Y;

	GC.SHOP_INV_SWAP_X = GC.INV_SWAP_X + GC.SHOP_INV_OFFSET_X;
	GC.SHOP_INV_SWAP_Y = GC.INV_SWAP_Y + GC.SHOP_INV_OFFSET_Y-160;
	GC.SHOP_INV_SWAP_W = GC.INV_SWAP_W-5;
	GC.SHOP_INV_SWAP_H = GC.INV_SWAP_H;

	GC.SHOP_INV_UNEQUIP_X = GC.SHOP_INV_SWAP_X+150;
	GC.SHOP_INV_UNEQUIP_Y = GC.SHOP_INV_SWAP_Y;
	GC.SHOP_INV_UNEQUIP_W = GC.SHOP_INV_SWAP_W;
	GC.SHOP_INV_UNEQUIP_H = GC.SHOP_INV_SWAP_H;

	GC.SHOP_BUTTONS_X = GC.SHOP_SELECTION_AREA_X+10;
	GC.SHOP_BUTTONS_W = 55;
	GC.SHOP_BUTTONS_H = 55;
	GC.SHOP_BUY_Y = GC.SHOP_SELECTION_AREA_Y+50;
	GC.SHOP_SELL_Y = GC.SHOP_BUY_Y+75;

	GC.SHOP_LENGTH = GC.SHOP_SLOTS_X*GC.SHOP_ROW_SLOTS;
	GC.SHOP_HEIGHT = GC.SHOP_SLOTS_Y*GC.SHOP_COL_SLOTS;

	GC.SHOP_GRID_X_OFFSET = 5;
	GC.SHOP_GRID_Y_OFFSET = 4;

	GC.SHOP_GRID_X = GC.SHOP_X+GC.SHOP_GRID_X_OFFSET;
	GC.SHOP_GRID_Y = GC.SHOP_Y+GC.SHOP_GRID_Y_OFFSET;

	//screenTabs
	GC.TAB_GAP = 10;
	GC.ALL_TABS_Y = GC.MAP_Y-30;
	GC.ALL_TABS_W = GC.MAP_W/5-GC.TAB_GAP;
	GC.ALL_TABS_H = 25.;

	GC.INV_TAB_X = GC.MAP_X+GC.TAB_GAP/2;
	GC.STATS_TAB_X = GC.INV_TAB_X+GC.ALL_TABS_W+GC.TAB_GAP;
	GC.MAP_TAB_X = GC.STATS_TAB_X+GC.ALL_TABS_W+GC.TAB_GAP;
	GC.QUESTS_TAB_X = GC.MAP_TAB_X+GC.ALL_TABS_W+GC.TAB_GAP;
	GC.SHOP_TAB_X = GC.QUESTS_TAB_X+GC.ALL_TABS_W+GC.TAB_GAP;

	GC.TAB_UNSELECTED_COLOR = "#565656";
	GC.TAB_SELECTED_COLOR = "#828282"

	//item arrays
	GC.ALL_SHOP_ITEMS = allItems.concat(allGems);
	GC.ALL_CHEST_ITEMS = allItems.concat(allGems);
}	


function setOpeningScreenConstants() {
	OSC = {
		GAMEMODE_BOX_X: canvas.width/2-75,
		GAMEMODE_BOX_Y: 6*canvas.height/8,
		GAMEMODE_BOX_W: 150,
		GAMEMODE_BOX_H: 50,

		LOAD_X: 20,
		LOAD_Y: canvas.height-60,
		LOAD_W: 100,
		LOAD_H: 40,
		
	}
		//not actually a button, could change name, only used in openingScreen.js
		OSC.NUM_LEVELS_BUTTON_W = 60;
		OSC.NUM_LEVELS_BUTTON_X = OSC.GAMEMODE_BOX_X + (OSC.GAMEMODE_BOX_W - OSC.NUM_LEVELS_BUTTON_W)/2; //centered
		OSC.NUM_LEVELS_BUTTON_Y = OSC.GAMEMODE_BOX_Y + OSC.GAMEMODE_BOX_H + 20;
		OSC.NUM_LEVELS_BUTTON_W = 60;
		OSC.NUM_LEVELS_BUTTON_H = 40;

		OSC.DOWN_LEVEL_X = OSC.NUM_LEVELS_BUTTON_X - 30;
		OSC.UP_LEVEL_X = OSC.NUM_LEVELS_BUTTON_X + OSC.NUM_LEVELS_BUTTON_W + 30;
		OSC.LEVEL_BUTTONS_Y = OSC.NUM_LEVELS_BUTTON_Y + OSC.NUM_LEVELS_BUTTON_H/2;
}
